### ISSUE TITLE
Locking Failed! when using Cookiecutter for Docker

### ISSUE THREAD

**Issue by michaelchen21** [awesto/cookiecutter-django-shop#10]
I ran the following:

```sh
cookiecutter https://github.com/awesto/cookiecutter-django-shop










America/New_York
y
3
n


n



y

```

In other words, this is setting the time zone, saying yes to using PyCharm, using uwsgi, not using i18n, not using Sendcloud, using the compressor (which is mandatory for using uwsgi), and using the defaults for the other settings.

In Git Bash, I got the following error:

```sh
Pipfile.lock not found, creating▒
Locking [dev-packages] dependencies▒
[   =] Locking..Success!
Locking [packages] dependencies▒
[   =] Locking..Locking Failed!
Traceback (most recent call last):
  File "C:/Users/micha/AppData/Roaming/Python/Python37/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "C:/Users/micha/AppData/Roaming/Python/Python37/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "C:/Users/micha/AppData/Roaming/Python/Python37/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "C:/Users/micha/AppData/Roaming/Python/Python37/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\micha\AppData\Local\Temp\tmpalw4bb1tbuild\uwsgi\
File "C:/Users/micha/AppData/Roaming/Python/Python37/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "C:/Users/micha/AppData/Roaming/Python/Python37/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "C:/Users/micha/AppData/Roaming/Python/Python37/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "C:/Users/micha/AppData/Roaming/Python/Python37/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Users\micha\AppData\Roaming\Python\Python37\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\micha\AppData\Local\Temp\tmpalw4bb1tbuild\uwsgi\
Traceback (most recent call last):
  File "C:\Users\micha\AppData\Local\Temp\tmpku41sldb.py", line 241, in <module>
    main()
  File "C:\Users\micha\AppData\Local\Temp\tmpku41sldb.py", line 229, in main
    pipenv_to_requirements()
  File "C:\Users\micha\AppData\Local\Temp\tmpku41sldb.py", line 171, in pipenv_to_requirements
    ret = subprocess.check_output(['pipenv', 'lock', '--requirements'])
  File "c:\users\micha\appdata\local\programs\python\python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\users\micha\appdata\local\programs\python\python37-32\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pipenv', 'lock', '--requirements']' returned non-zero exit status 1.
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

I got a similar Locking Failed error using Command Prompt, but without the traceback.

I was able to use the cookiecutter script successfully previously when using dockerize - n (also, I just realized that the *n* in dockerize - n and delivery_handling - n means no, and not some number n). Trying this with runserver also resulted in the same error.

I'm using Windows 10 Home v1903.

**Comment by Yattus** [comment]
Don't make choose here, when ask dockerize, let default do just **enter** and that will work fine.
But if you want to use it or run it on docker, follow that [https://github.com/awesto/cookiecutter-django-shop#run-django-shop-demo-in-docker](url).
