### ISSUE TITLE
Cannot login with user:admin pass:secret after intializing

### ISSUE THREAD

**Issue by kennette21** [awesto/cookiecutter-django-shop#13]
## What happened?
I followed the tutorial and when i try to login with the given credentials i see this error message on the page: 
"Please enter the correct email address and password for a staff account. Note that both fields may be case-sensitive."

## What should've happened instead?
I should have been able to login and see the application.

Stack trace:
https://dpaste.de/DmF1

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Project generation options)
[//]: # (* Logs)

**Comment by kennette21** [comment]
I am suspicious the app was not properly initialized. When I run `python manage.py migrate` I see there are operations to perform, but none are applied. This is what the migrate command returns:
```
/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/shop/admin/product.py:106: UserWarning:
Your caching backend does not support deletion by key patterns.
Please use 'django-redis-cache', or wait until the product's HTML
snippet cache expires by itself.
  warnings.warn("\n"
Operations to perform:
  Apply all migrations: admin, auth, authtoken, cms, cmsplugin_cascade, contenttypes, djangocms_text_ckeditor, easy_thumbnails, email_auth, filer, menus, myshop, post_office, sessions, shop, sites
Running migrations:
  No migrations to apply.
```

**Comment by kennette21** [comment]
I looked into the auth tables to try and see what was wrong with the admin user, but all of the tables are empty, which is why I think the demo has not been initialized properly.

**Comment by kennette21** [comment]
Realizing now that something broke in the middle of the `manage.py initialize_shop_demo` and the `.initialize` file gets removed, but the full script breaks before finishing. This means that the db gets initialized, but it gets no data loaded into it. Here is the error that breaks the initialize command:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/tbean/Projects/testShop/my-shop/myshop/management/commands/initialize_shop_demo.py", line 43, in handle
    call_command('loaddata', 'skeleton')
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 115, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 286, in check_constraints
    column_name, referenced_column_name,
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/tbean/.virtualenvs/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: Problem installing fixtures: no such table: filer_folder__old
```

**Comment by kennette21** [comment]
subsequent calls to initialize fail because there is no `.initialize` file

**Comment by jrief** [comment]
The `.initialize` should only be removed after a successful download. May it be that something was aborted, or the file unintentionally removed?

**Comment by moellering** [comment]
The .initialize file is removed after the migrations have been run and before installing the skeletons file, downloading media files and loading media files. 
It's the same for for the [master branch](https://github.com/awesto/cookiecutter-django-shop/blob/7fc5eeff23354904a01b1e0483a193661d1531c0/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/management/commands/initialize_shop_demo.py#L61), the [releases/1.0](https://github.com/awesto/cookiecutter-django-shop/blob/d05d4be159604f0946c144554d4dfc8349d2777a/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/management/commands/initialize_shop_demo.py#L56) and the [releases/1.1](https://github.com/awesto/cookiecutter-django-shop/blob/c6abdfc740ac77a6d8e362e3b07d230b0639a26d/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/management/commands/initialize_shop_demo.py#L61)

You can `touch workdir/.initialize`the file to run the `initialize_shop_demo` command again. You might have to remove workdir/db.sqlite3 before doing it if the error has screwed up you installation.

**Comment by moellering** [comment]
@kennette21 I just noticed, that the second error you are receiving is the `no such table: filer_folder__old` error I mentioned in #14 
You might want to have a look at the workaround there for a temporary solution.

**Comment by kennette21** [comment]
hey @moellering, thanks for the tips! I did what your first said when i was trying to solve the problem actually! 

Eventually I fixed it by using pipenv properly as described in the setup process 😅. I tried to setup my own virtualenv and messed up somewhere along the way. Thanks for the help!!
