### ISSUE TITLE
fallback.svg is used instead of images

### ISSUE THREAD

**Issue by moellering** [awesto/cookiecutter-django-shop#15]
## What happened before?
Images (in my case the product images on the details page of the earphones) showed up. On `http://localhost:8000/de/` there was a unicorn.

## What happens now?
`/static/cascade/fallback.svg` is used instead of the actual images.

## Last stable commit / Since when?
The images work properly on master (current commit 7fc5eeff23354904a01b1e0483a193661d1531c0) and do not work on releases/1.1 (current commit 7fc5eeff23354904a01b1e0483a193661d1531c0)

## Steps to reproduce
```bash 
cookiecutter https://github.com/awesto/cookiecutter-django-shop --checkout releases/1.1
```
use defaults
```bash
cd my-shop
pipenv install --sequential
npm install
pipenv run ./manage.py initialize_shop_demo
export DJANGO_DEBUG=1
pipenv run ./manage.py runserver
```

**Comment by jrief** [comment]
In Cascade, the fallback image has been added to the Jumbotron. However, according to the Bootstrap-4 specs, a Jumbotron does not need an image; for instance just adding a background color should work fine. Therefore in Cascade-1.1 it the fallback image has been removed.

**Comment by moellering** [comment]
I cleared up the original report. The problem is not that the fallback images is not used. The problem is that the fallback image is used instead of the right image.

**Comment by haricot** [comment]
It is possible that you are using a version that does not already contain
Django cms fixtures.
Can you put the result of the command from scratch.

./manage.py initialize_shop_demo





Le mar. 22 oct. 2019 à 12:44, moellering <notifications@github.com> a
écrit :

**Comment by moellering** [comment]
Since the products from the fixtures are in the database, at least some of the fixtures must have been loaded. 

When I go into edit mode I can see that the image cascade plugin does not have an image set. The images themselves are there since I can select them in the settings of the image cascade plugin. After setting the images manually, they are shown properly. 
This might indicate that the json for the plugin which is set by the fixtures is not working as intended.


None of the fixtures shows an error though: 
<details>
  <summary>output of pipenv run ./manage.py initialize_shop_demo (click to expand)</summary>
<pre>/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/shop/admin/product.py:110: UserWarning: 
Your caching backend does not support deletion by key patterns.
Please use 'django-redis-cache', or wait until the product's HTML
snippet cache expires by itself.
  warnings.warn("\n"
Operations to perform:
  Apply all migrations: admin, auth, authtoken, cms, cmsplugin_cascade, contenttypes, djangocms_text_ckeditor, easy_thumbnails, email_auth, filer, menus, post_office, sessions, shop, shop_sendcloud, sites
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying email_auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cms.0004_auto_20140924_1038... OK
  Applying cms.0005_auto_20140924_1039... OK
  Applying cms.0006_auto_20140924_1110... OK
  Applying cms.0007_auto_20141028_1559... OK
  Applying cms.0008_auto_20150208_2149... OK
  Applying cms.0008_auto_20150121_0059... OK
  Applying cms.0009_merge... OK
  Applying cms.0010_migrate_use_structure... OK
  Applying cms.0011_auto_20150419_1006... OK
  Applying cms.0012_auto_20150607_2207... OK
  Applying cms.0013_urlconfrevision... OK
  Applying cms.0014_auto_20160404_1908... OK
  Applying cms.0015_auto_20160421_0000... OK
  Applying cms.0016_auto_20160608_1535... OK
  Applying cms.0017_pagetype... OK
  Applying cms.0018_create_pagenode... OK
  Applying cms.0019_set_pagenode... OK
  Applying cms.0020_old_tree_cleanup... OK
  Applying cms.0021_auto_20180507_1432... OK
  Applying cms.0022_auto_20180620_1551... OK
  Applying filer.0001_initial... OK
  Applying filer.0002_auto_20150606_2003... OK
  Applying filer.0003_thumbnailoption... OK
  Applying filer.0004_auto_20160328_1434... OK
  Applying filer.0005_auto_20160623_1425... OK
  Applying filer.0006_auto_20160623_1627... OK
  Applying cmsplugin_cascade.0001_initial... OK
  Applying cmsplugin_cascade.0002_auto_20150530_1018... OK
  Applying cmsplugin_cascade.0003_inlinecascadeelement... OK
  Applying cmsplugin_cascade.0004_auto_20151112_0147... OK
  Applying cmsplugin_cascade.0005_tabset_and_clipboard... OK
  Applying cmsplugin_cascade.0006_bootstrapgallerypluginmodel... OK
  Applying cmsplugin_cascade.0007_add_proxy_models... OK
  Applying cmsplugin_cascade.0008_sortableinlinecascadeelement... OK
  Applying cmsplugin_cascade.0009_cascadepage... OK
  Applying cmsplugin_cascade.0010_refactor_heading... OK
  Applying cmsplugin_cascade.0011_merge_sharable_with_cascadeelement... OK
  Applying cmsplugin_cascade.0012_auto_20160619_1854... OK
  Applying cmsplugin_cascade.0013_iconfont... OK
  Applying cmsplugin_cascade.0014_glossary_field... OK
  Applying cmsplugin_cascade.0015_carousel_slide... OK
  Applying cmsplugin_cascade.0016_shared_glossary_uneditable... OK
  Applying cmsplugin_cascade.0017_fake_proxy_models... OK
  Applying cmsplugin_cascade.0018_iconfont_color... OK
  Applying cmsplugin_cascade.0019_verbose_table_names... OK
  Applying cmsplugin_cascade.0020_page_icon_font...Skipping this migration.
 OK
  Applying cmsplugin_cascade.0021_cascadepage_verbose_name... OK
  Applying cmsplugin_cascade.0022_auto_20181202_1055... OK
  Applying cmsplugin_cascade.0023_iconfont_is_default... OK
  Applying cmsplugin_cascade.0024_page_icon_font... OK
  Applying cmsplugin_cascade.0025_texteditorconfigfields... OK
  Applying cmsplugin_cascade.0026_cascadepage_menu_symbol... OK
  Applying cmsplugin_cascade.0027_version_1... OK
  Applying djangocms_text_ckeditor.0001_initial... OK
  Applying djangocms_text_ckeditor.0002_remove_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_text_ckeditor.0003_set_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_text_ckeditor.0004_auto_20160706_1339... OK
  Applying easy_thumbnails.0001_initial... OK
  Applying easy_thumbnails.0002_thumbnaildimensions... OK
  Applying email_auth.0002_auto_20160327_1119... OK
  Applying email_auth.0003_django110... OK
  Applying email_auth.0004_auto_20170411_1733... OK
  Applying filer.0007_auto_20161016_1055... OK
  Applying filer.0008_auto_20171117_1313... OK
  Applying filer.0009_auto_20171220_1635... OK
  Applying filer.0010_auto_20180414_2058... OK
  Applying filer.0011_auto_20190418_0137... OK
  Applying menus.0001_initial... OK
  Applying post_office.0001_initial... OK
  Applying post_office.0002_add_i18n_and_backend_alias... OK
  Applying post_office.0003_longer_subject... OK
  Applying post_office.0004_auto_20160607_0901... OK
  Applying post_office.0005_auto_20170515_0013... OK
  Applying post_office.0006_attachment_mimetype... OK
  Applying post_office.0007_auto_20170731_1342... OK
  Applying post_office.0008_attachment_headers... OK
  Applying sessions.0001_initial... OK
  Applying shop.0001_initial... OK
  Applying shop.0002_auto_20151016_1451... OK
  Applying shop.0003_glossary_fields... OK
  Applying shop.0004_ckeditor31... OK
  Applying shop.0005_unify_address... OK
  Applying shop.0006_rename_to_catalog... OK
  Applying shop.0007_notification_recipient... OK
  Applying shop.0008_notification_recipient... OK
  Applying shop.0009_delete_email... OK
  Applying shop_sendcloud.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
Initializing project myshop
Migrations for 'myshop':
  myshop/migrations/0001_initial.py
    - Create model BillingAddress
    - Create model Cart
    - Create model CartItem
    - Create model Customer
    - Create model Delivery
    - Create model DeliveryItem
    - Create model Manufacturer
    - Create model OperatingSystem
    - Create model Order
    - Create model OrderItem
    - Create model OrderPayment
    - Create model Product
    - Create model ProductImage
    - Create model ProductPage
    - Create model ProductTranslation
    - Create model ShippingAddress
    - Create model SmartCardTranslation
    - Create model SmartPhoneModelTranslation
    - Create model SmartPhoneVariant
    - Create model Commodity
    - Create model SmartCard
    - Create model SmartPhoneModel
    - Add field master to producttranslation
    - Add field product to productpage
    - Add field product to productimage
    - Add field cms_pages to product
    - Add field images to product
    - Add field manufacturer to product
    - Add field polymorphic_ctype to product
    - Add field product to orderitem
    - Add field item to deliveryitem
    - Add field order to delivery
    - Add field product to cartitem
    - Add field customer to cart
    - Add field shipping_address to cart
    - Add field customer to billingaddress
    - Add field product to smartphonevariant
    - Add field master to smartphonemodeltranslation
    - Add field master to smartcardtranslation
    - Alter unique_together for producttranslation (1 constraint(s))
    - Alter unique_together for productpage (1 constraint(s))
    - Alter unique_together for delivery (1 constraint(s))
    - Alter unique_together for smartphonemodeltranslation (1 constraint(s))
    - Alter unique_together for smartcardtranslation (1 constraint(s))
Operations to perform:
  Apply all migrations: admin, auth, authtoken, cms, cmsplugin_cascade, contenttypes, djangocms_text_ckeditor, easy_thumbnails, email_auth, filer, menus, myshop, post_office, sessions, shop, shop_sendcloud, sites
Running migrations:
  Applying myshop.0001_initial... OK
Installed 33 object(s) from 1 fixture(s)
The following CMS pages must be adjusted:
^P 1. Created recommended CMS home page.
 2. Created recommended CMS page 'Legal'.
 3. Created recommended CMS page 'Imprint'.
 4. Created recommended CMS page 'Terms and Conditions'.
 5. Created recommended CMS page 'Privacy Protection'.
 6. Created recommended CMS page 'Personal Pages'.
 7. Created recommended CMS page 'Join Us'.
 1. Created CMS page titled 'Catalog'.
 2. Created mandatory CMS page titled 'Search'.
 3. Created mandatory CMS page titled 'Cart'.
 4. Created mandatory CMS page titled 'Watch-List'.
 5. Created mandatory CMS page titled 'Your Orders'.
 6. Created mandatory CMS page titled 'Personal Details'.
 7. Created mandatory CMS page titled 'Change Password'.
 8. Created mandatory CMS page titled 'Login'.
 9. Created mandatory CMS page titled 'Register Customer'.
 10. Created mandatory CMS page titled 'Request Password Reset'.
 11. Created mandatory CMS page titled 'Confirm Password Reset'.
 12. Created mandatory CMS page titled 'Payment Canceled'.
 13. Created CMS page titled 'Checkout'
Added Social Icons to Static Placeholder
Downloading workdir and extracting to /home/kevin/tmp/test_cookiecutter_djangoshop/my-shop/workdir/... Please wait ...
Installed 192 object(s) from 1 fixture(s)
1. Apple iPhone 5
2. Super Darts
3. Nexus 4
4. Sennheiser HD630VB
5. Galaxy S6 active
6. Backbeat FIT
7. Sony Xperia TL
9. Motorola Atrix
10. Kyocera Hydro Edge
11. HTC Evo design 4G
12. HTC Thunderbolt
13. LG Connect 4G
14. DROID 3
15. Samsung Galaxy S III
16. SDXC Card 64GB
17. Kyocera Milano
18. SDHC Card 4GB
19. SDHC Card 8GB
20. SDHC Card 16GB
21. SDHC Card 32GB
22. EXTREME PLUS microSDHC 32GB
23. EXTREME PLUS microSDXC 64GB
24. EXTREME PLUS SDHC 16GB
25. EXTREME PLUS SDHC 32GB
26. EXTREME PLUS SDXC 64GB
27. Extreme PRO microSDHC 32GB
28. EXTREME PLUS microSDHC 16GB
29. Extreme PRO microSDXC 64GB
30. Extreme PRO SDHC 16GB
31. Extreme PRO SDHC 32GB
32. Extreme PRO SDXC 64GB
33. Extreme PRO SDXC 128GB
34. Extreme PRO SDXC 256GB
35. Extreme PRO SDXC 512GB
36. Extreme PRO SDHC II 16GB
37. Extreme PRO SDHC II 32GB
38. Extreme PRO SDXC II 64GB
39. Micro SDHC 32GB
40. Micro SDHC 64GB
41. Ultra SDHC 8GB 40Mb/s
42. Ultra SDHC 16GB 40MB/s
43. Ultra SDHC 32GB 40Mb/s
44. Ultra SDXC 64GB 40Mb/s
45. Ultra SDXC 128GB 40Mb/s
46. Ultra PLUS SDHC 16GB
47. Ultra SDHC 16GB 30Mb/s
48. Ultra PLUS SDXC 128GB
49. Ultra SDHC 32GB 30Mb/s
50. Ultra PLUS micro SDXC 64GB
51. Ultra PLUS micro SDHC 16GB
52. Ultra PLUS micro SDHC 32GB
53. Ultra PLUS micro SDXC 128GB
54. Ultra SDXC 64GB 30Mb/s
55. Ultra PLUS SDXC 64GB
56. Ultra PLUS SDHC 32GB
</pre>
</details>

**Comment by haricot** [comment]
in "environment that does not show images (click to expand)" :
you use django-cms = 3.7, which have no fixtures.
your last `./manage.py initialize_shop_demo ` does not include the command enviroment.

**Comment by moellering** [comment]
> you use django-cms = 3.7, which have no fixtures.

- The Pipfile of release/1.1 includes a reference to `djangocms-cascade = ">=1.0"`
This leads to the installation of djangocms-cascade==1.1.2
This in turn has a dependency on `'django-cms>=3.5,<4'` in its setup.py
Thus 3.7 gets installed. 
Is this a problem? Then we might have to add a dependency to django-cms<3.7.0 to the cookie cutter template.

- I could not find anything in the release notes regarding fixtures. I'm not sure if I interpret your sentence correctly. Could you please rephrase it?

> your last ./manage.py initialize_shop_demo does not include the command enviroment.

I'm executing it inside the environment listed in `environment that does not show images (release/1.1) (click to expand)`

**Comment by moellering** [comment]
I've just installed it again and tried to run release/1.1 on django-cms 3.6 to rule out a problem with django-cms 3.7. I used the following commands

```
mkvirtualenv cookiecutter-django-shop
pip install cookiecutter autopep8 pipenv
cookiecutter https://github.com/awesto/cookiecutter-django-shop --checkout releases/1.1 # (n to papal, stripe and send_cloud; rest defaults)
cd my-shop
pipenv install --sequential
pip install "django-cms<3.7.0"
pipenv run ./manage.py initialize_shop_demo
export DJANGO_DEBUG=1
pipenv run ./manage.py runserver
```
while the migrations script states that there are changes without migrations, the server runs also runs on djangocms-3.6 (as long as i don't try to login). However, this does not change a thing about the cascade image plugins. They are showing the fallback image.

My environment is now:
<details><summary>click to expand</summary><pre>
pip freeze
arrow==0.15.2
autopep8==1.4.4
Babel==2.7.0
binaryornot==0.4.4
certifi==2019.9.11
chardet==3.0.4
Click==7.0
cookiecutter==1.6.0
defusedxml==0.6.0
Django==1.11.25
django-admin-sortable2==0.7.3
django-angular==2.2.3
django-appconf==1.0.3
django-classy-tags==0.9.0
django-cms==3.6.0
django-entangled==0.3
django-filer==1.5.0
django-filter==2.2.0
django-formtools==2.1
django-fsm==2.6.1
django-fsm-admin==1.2.4
django-haystack==2.8.1
django-ipware==2.1.0
django-js-asset==1.2.2
django-mptt==0.10.0
django-parler==2.0
django-parler-rest==2.0
django-phonenumber-field==3.0.1
django-polymorphic==1.3.1
django-post-office==3.2.1
django-rest-auth==0.9.5
django-sass-processor==0.7.3
django-sekizai==1.0.0
django-select2==6.3.1
django-shop==1.1.dev0
django-treebeard==4.3
djangocms-admin-style==1.4.0
djangocms-bootstrap==1.1.2
djangocms-cascade==1.1.2
djangocms-text-ckeditor==3.8.0
djangorestframework==3.8.2
drf-haystack==1.8.6
easy-thumbnails==2.6
elasticsearch==1.7.0
future==0.18.1
html5lib==1.0.1
idna==2.8
Jinja2==2.10.3
jinja2-time==0.2.0
jsonfield==2.0.2
libsass==0.19.3
MarkupSafe==1.1.1
oauthlib==3.1.0
phonenumbers==8.10.21
Pillow==6.2.1
pipenv==2018.11.26
poyo==0.5.0
pycodestyle==2.5.0
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2019.3
requests==2.22.0
requests-oauthlib==1.2.0
six==1.12.0
Unidecode==1.0.23
urllib3==1.25.6
virtualenv==16.7.7
virtualenv-clone==0.5.3
webencodings==0.5.1
whichcraft==0.6.1
</pre></details

**Comment by haricot** [comment]
There are no fixtures for versions of djangocms 3.6 and 3,7 because a new version of django-shop is planned for November, it seems to me that the fictures exsite only for cms = 3.5

**Comment by haricot** [comment]
> your last ./manage.py initialize_shop_demo does not include the command enviroment.

> output of pipenv run ./manage.py initialize_shop_demo (click to expand)`

with django-cms == 3.7 the fixtures should have failed, so i conclude that the output does not correspond to the environment mention (no image)

**Comment by haricot** [comment]
if you really want fixture, force install `django-cms==3.5`
and lanch `./manage.py initialize_shop_demo`, and update with `django-cms == 3.6` or 3.7
it may work without waiting.

**Comment by moellering** [comment]
Ok thanks for the detailed information :)

To try out your suggestion with django-cms==3.5 I just ran initialize_shop_demo on an environment with django-cms 3.5.0 installed. After that I installed 3.7. The output of the fixtures is the same as [above](https://github.com/awesto/cookiecutter-django-shop/issues/15#issuecomment-544927283).

runserver works after that and again shows only the fallback images are shown (both on article pages and on the home page). There are then still 4 unapplied migrations. Trying to apply them yields `CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0022_auto_20180620_1551, 0019_auto_20191022_1419 in cms).`
Running the suggested `python manage.py makemigrations --merge` and then appyling the migration works, but does not change the fallback images. They are still shown instead of the cascade image plugins.

I a second attempt installed "djangocms-cascade<1.1" before running initialize_shop_demo. I endet up with django-cms==3.6.0 and djangocms-cascade-1.0. The ouptut of `initialize_shop_demo` is the same as above (i.e. no errors) but running the whole thing still gives me the fallback image instead of the pretty unicorn.

Next Try: By using `pip install "djangocms-cascade<1.0"` I endet up with `django-cms-3.5.3`and  `djangocms-cascade-0.19`. Now `initialize_shop_demo` greets me with  the following error:
<details><summary>djangocms 3.5.3 and djangocms-cascade-0.19 on release/1.1 branch (click to expand)</summary>
<pre>Traceback (most recent call last):
  File "/home/kevin/tmp/test_cookiecutter_djangoshop/my-shop/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/cms/admin/__init__.py", line 11, in <module>
    plugin_pool.plugin_pool.discover_plugins()
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/cms/plugin_pool.py", line 45, in discover_plugins
    autodiscover_modules('cms_plugins')
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/cmsplugin_cascade/cms_plugins.py", line 17, in <module>
    import_module('{}.{}'.format(module, p))
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/cmsplugin_cascade/bootstrap4/buttons.py", line 15, in <module>
    from cmsplugin_cascade.link.config import LinkPluginBase, LinkElementMixin, LinkForm
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/cmsplugin_cascade/link/config.py", line 10, in <module>
    for cls in app_settings.CMSPLUGIN_CASCADE['link_plugin_classes'])
</pre></details>



Since I did not see fails: How should the fixtures fail on django-cms>=3.6?

**Comment by haricot** [comment]
Thé file .initialise needed  to be removed before:
./manage.py initialize_shop_demo 
Should end up saying that he does not find to download the fixtures.
.

**Comment by moellering** [comment]
But when i remove the .initialize file, no fixtures are imported. I'm not sure how this would help me get the fixtures installed on a <3.6 django-cms environment.

However: since the fixture installation problems also seems to influence the functionality of the "order" buttons, I don't think I can use this version to test new fixes. I'm now trying to get the 1.0 release running. You can follow those attempts in the next issues.
