### ISSUE TITLE
Installing releases/1.0 adds unknown package html_email INSTALLED_APPS

### ISSUE THREAD

**Issue by moellering** [awesto/cookiecutter-django-shop#17]
## What happened?
After Installation (no stripe, no paypal, no sendcloud - all other settings like default) and using the workaround for Issue #16 `initialize_shop_demo` crashed with the error
```
Traceback (most recent call last):
  File "/home/kevin/tmp/test_cookiecutter_djangoshop/my-shop/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/home/kevin/.virtualenvs/cookiecutter-django-shop/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'html_email'
```

## What should've happened instead?
`pipenv run ./manage.py initialize_shop_demo` should run migrations and install fixtures.

## Steps to reproduce
```
cookiecutter https://github.com/awesto/cookiecutter-django-shop --checkout releases/1.0 # paypal, stripe and sendcloud -> no; other settings default
cd my-shop
# replace select2 line in Pipfile (see #16 )
pipenv install --sequential
pipenv run ./manage.py initialize_shop_demo
```

**Comment by jrief** [comment]
does this still occur?
