### ISSUE TITLE
Locking Failed!

### ISSUE THREAD

**Issue by Housain-maina** [awesto/cookiecutter-django-shop#19]
## What happened?
F:\PC\Shop\my-sopping-mall>pipenv install --sequential
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking Failed!
Traceback (most recent call last):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 331, in _error_catcher
    yield
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 413, in read
    data = self._fp.read(amt)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 279, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 674, in unpack_http_url
    progress_bar)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 898, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 618, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\utils\hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 586, in written_chunks
    for chunk in chunks:
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 575, in resp_read
    decode_content=False):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 336, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pipenv.patched.notpip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 331, in _error_catcher
    yield
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 413, in read
    data = self._fp.read(amt)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 279, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 674, in unpack_http_url
    progress_bar)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 898, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 618, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\utils\hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 586, in written_chunks
    for chunk in chunks:
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 575, in resp_read
    decode_content=False):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 336, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pipenv.patched.notpip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

F:\PC\Shop\my-sopping-mall> pipenv lock --clear
Locking [dev-packages] dependencies…
Locking Failed!
Traceback (most recent call last):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 331, in _error_catcher
    yield
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 413, in read
    data = self._fp.read(amt)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 279, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 674, in unpack_http_url
    progress_bar)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 898, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 618, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\utils\hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 586, in written_chunks
    for chunk in chunks:
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 575, in resp_read
    decode_content=False):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 336, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pipenv.patched.notpip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 331, in _error_catcher
    yield
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 413, in read
    data = self._fp.read(amt)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "C:/Users/MAINA/AppData/Roaming/Python/Python36/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 279, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 674, in unpack_http_url
    progress_bar)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 898, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 618, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\utils\hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 586, in written_chunks
    for chunk in chunks:
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_internal\download.py", line 575, in resp_read
    decode_content=False):
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\MAINA\AppData\Local\Programs\Python\Python36\Lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\MAINA\AppData\Roaming\Python\Python36\site-packages\pipenv\patched\notpip\_vendor\urllib3\response.py", line 336, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pipenv.patched.notpip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

## What should've happened instead?

Lock pipfile

**Comment by jrief** [comment]
Please learn how to create meaningful issues!

**Comment by Housain-maina** [comment]
Thank you for replying in this manner.
