### ISSUE TITLE
Cannot get runserver or docker image to work due to error

### ISSUE THREAD

**Issue by Rubenvanv** [awesto/cookiecutter-django-shop#50]
## What happened?

Installing django-shop and running into the following issue

SystemCheckError: System check identified some issues:

ERRORS:
<class 'filer.admin.folderadmin.FolderAdmin'>: (admin.E039) An admin for model "User" has to be registered to be referenced by FolderAdmin.autocomplete_fields.
<class 'filer.admin.permissionadmin.PermissionAdmin'>: (admin.E039) An admin for model "User" has to be registered to be referenced by PermissionAdmin.autocomplete_fields.

System check identified 2 issues (1 silenced).

## What should've happened instead?

full log 

(base) MacBook-Pro-3:my-shop ruben$ pipenv run ./manage.py runserver
/Users/ruben/.local/share/virtualenvs/my-shop--4zjYMH3/lib/python3.7/site-packages/shop/apps.py:32: UserWarning: 
Your caching backend does not support invalidation by key pattern.
Please use `django-redis-cache`, or wait until the product's HTML
snippet cache expires by itself.
  warnings.warn("\n"
/Users/ruben/.local/share/virtualenvs/my-shop--4zjYMH3/lib/python3.7/site-packages/shop/apps.py:32: UserWarning: 
Your caching backend does not support invalidation by key pattern.
Please use `django-redis-cache`, or wait until the product's HTML
snippet cache expires by itself.
  warnings.warn("\n"
[2021-11-14 12:18:06,783 autoreload] INFO: Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/ruben/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/ruben/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ruben/.local/share/virtualenvs/my-shop--4zjYMH3/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/ruben/.local/share/virtualenvs/my-shop--4zjYMH3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/ruben/.local/share/virtualenvs/my-shop--4zjYMH3/lib/python3.7/site-packages/django/core/management/base.py", line 441, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<class 'filer.admin.folderadmin.FolderAdmin'>: (admin.E039) An admin for model "User" has to be registered to be referenced by FolderAdmin.autocomplete_fields.
<class 'filer.admin.permissionadmin.PermissionAdmin'>: (admin.E039) An admin for model "User" has to be registered to be referenced by PermissionAdmin.autocomplete_fields.

System check identified 2 issues (1 silenced).

## Steps to reproduce

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Project generation options)
[//]: # (* Logs)

**Comment by iniadewumi** [comment]
Have you been able to figure this out? I am having the same issue.
Attempted to create new user model, but that doesn't fix the issue

**Comment by Rubenvanv** [comment]
Nope this thing just seems broken I am moving on to another shopping card system what a pitty

**Comment by Rubenvanv** [comment]
I will try tonight and let you know

Thank you,

Ruben

**Comment by mycosavant** [comment]
I am having this same error and have tried to follow the above instructions but there must be something I'm missing. I can't find the file `requirements.txt` anywhere. I have searched and found references to it within the repository but when i follow the docs for installation the file is not even created. 
I would prefer to not use Docker at all, and just run the project locally. I've tried to complete the process several times and it is always failing.

**Comment by alfor** [comment]
Same error for me, just lost time trying to make it work.
It’s unmaintained, use something else.

https://github.com/awesto/django-shop/issues/873
