### ISSUE TITLE
error when you run the command docker-compose up --build -d

### ISSUE THREAD

**Issue by stilet** [awesto/cookiecutter-django-shop#6]
Ubuntu 18.04

Select dockerize: 2
use_i18n [y]
Select products_model:[2]
use_compressor [n]: y

Step 28/34 : RUN ./manage.py compilescss
ocal/lib/python3.6/site-packages/shop/admin/product.py:109: UserWarning:
Your caching backend does not support deletion by key patterns.
Please use 'django-redis-cache', or wait until the product's HTML
snippet cache expires by itself.
  warnings.warn("\n"
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 153, in handle
    self.parse_source(py_source)
  File "/usr/local/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 199, in parse_source
    tree = ast.parse(open(filename, 'rb').read())
  File "/usr/local/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 49
    def handle(self, verbosity, *args, **options):
                                                 ^
IndentationError: unindent does not match any outer indentation level
ERROR: Service 'wsgiapp' failed to build: The command '/bin/sh -c ./manage.py compilescss' returned a non-zero code: 1

**Comment by jrief** [comment]
Seems to be an error in https://github.com/jrief/django-sass-processor/edit/master/sass_processor/management/commands/compilescss.py , so please report it to the proper project. However, I can't find any indention error there.
